Project.MVCUI/Controllers/TicketshoppingController.cs
using Microsoft.Ajax.Utilities;
using PagedList;
using Project.BLL.Repositories.ConcRep;
using Project.COMMON.Tools;
using Project.ENTITIES.Enums;
using Project.ENTITIES.Models;
using Project.MVCUI.Models.PageVMs;
using Project.MVCUI.OuterRequestTool;
using Project.VM.PureVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Net.Sockets;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Project.MVCUI.Controllers
{
    public class TicketshoppingController : Controller
    {
        // GET: Automation
        SessionRepository _sRep;
        MovieRepository _mRep;
        ReservationRepository _rRep;
        OrderRepository _oRep;
        TicketRepository _tRep;
        OrderDetailRepository _oDetailRep;
        SalonRepository _saRep;
        public TicketshoppingController()
        {
            _oRep = new OrderRepository();
            _sRep = new SessionRepository();
            _rRep = new ReservationRepository();
            _mRep = new MovieRepository();
            _tRep = new TicketRepository();
            _oDetailRep = new OrderDetailRepository();
            _saRep = new SalonRepository();
        }
        public ActionResult MovieList() //
        {
            ListMoviePageVM l = new ListMoviePageVM
            {
                Movies = NotPassivTicketsMovies().Where(x =>x.ReleaseDate.Date <= DateTime.Now.Date && x.TakedownDate.Date >= DateTime.Now.Date).ToList(),
            };
            return View(l);
        }
        public ActionResult TakeTicket(string title)
        {
            return ListSeatPageVM(title);
        }
        [HttpPost]
        public ActionResult TakeTicket(string filmTitle,TicketVM ticket)
        {
            if (_tRep.Any(x => x.SeatNumber == ticket.SeatNumber && x.SessionID == ticket.ID) || _rRep.Any(x => x.ResSeatNo == ticket.SeatNumber && x.SessionID == ticket.ID))
            {
                TempData["var"] = "Sectiğiniz koltuk dolu";
                return ListSeatPageVM(filmTitle);
            }
            else if (ticket.TicketDate.Date >= DateTime.Now.Date)
            {
                if (Session["vip"] != null && ticket.TicketDate.Date <= DateTime.Now.AddDays(7).Date && ticket.SessionTime != null)
                {
                    Ticket t = new Ticket();
                    t.Session = _sRep.FirstOrDefault(x =>x.SessionTime == ticket.SessionTime);
                    t.SeatNumber = ticket.SeatNumber;
                    t.Type = TicketType.Ticket;
                    t.Session.TotalRatio++;
                    t.TicketDate = ticket.TicketDate.Date;
                    _tRep.Add(t);
                    return RedirectToAction("ConfirmOrder", t);
                }
                else if (ticket.TicketDate.Date <= DateTime.Now.AddDays(2).Date && ticket.SessionTime != null)
                {
                    Ticket t = new Ticket();
                    Session["session"] = t.Session = _sRep.FirstOrDefault(x => x.SessionTime == ticket.SessionTime);
                    t.SeatNumber = ticket.SeatNumber;
                    t.Type = TicketType.Ticket;
                    t.Session.TotalRatio++;
                    t.TicketDate = ticket.TicketDate.Date;
                    _tRep.Add(t);
                    return RedirectToAction("ConfirmOrder", t);
                }
                TempData["vipbug"] = Session["vip"] != null ? "You can buy tickets at least 7 days in advance" : null;
                TempData["bug"] = ticket.SessionTime== null ? "Select a session " : "You can buy tickets at least 2 days in advance";
                return RedirectToAction("TakeTicket", new { title = filmTitle });
            }
            TempData["time"] = "You can buy tickets at least 2 days in advance";
            return ListSeatPageVM(filmTitle);


        }
        public ActionResult MakeReservation(string title)
        {
            return ListSeatPageVM(title);
        }
        [HttpPost]
        public ActionResult MakeReservation(string filmTitle, ReservationVM reservation)
        {
            if (reservation.ID != 0 && reservation.SessionTime.Date <= DateTime.Now.AddDays(2).Date)
            {
                if (_tRep.Any(x => x.SeatNumber == reservation.ResSeatNumber && x.SessionID == reservation.ID) || _rRep.Any(x => x.ResSeatNo == reservation.ResSeatNumber && x.SessionID == reservation.ID))
                {
                    TempData["var"] = "Sectiğiniz koltuk dolu";
                    return ListSeatPageVM(filmTitle);
                }
                else
                {
                    Reservation r = new Reservation();
                    r.Session = _sRep.Find(reservation.ID);
                    r.Type = TicketType.Rez;
                    r.Customer = Session["customer"] as Customer != null ? Session["customer"] as Customer : Session["vip"] as Customer;
                    r.ResSeatNo = reservation.ResSeatNumber;
                    r.SessionID = reservation.SessionID;
                    r.TicketTime = reservation.SessionTime.Date;
                    _rRep.Add(r);
                    return RedirectToAction("ReservationInfo");
                }
               
            }
            TempData["badsession"] = "Select a session ";
            return RedirectToAction("MakeReservation", new { title = filmTitle });
        }
        public ActionResult ReservationInfo()
        {
            return View();
        }
        public ActionResult OrderInfo()
        {
            return View();
        }
        public ActionResult ConfirmOrder()
        {
            return View(); 
        }
        [HttpPost]
        public ActionResult ConfirmOrder(OrderPageVM orderPage,Ticket t)
        {
            if (orderPage.Save == true)
            {
                orderPage.PaymentRequestModel = (Session["kart"] as OrderPageVM).PaymentRequestModel;
            }
            if ((Session["vip"] as Customer) != null)
            {
                if (DateTime.Now > (Session["vip"] as Customer).MonthlyDate.AddMonths(1))
                {
                    (Session["vip"] as Customer).Monthly = true;
                    (Session["vip"] as Customer).FriendPayed = 2;
                }
            }
            if ((Session["vip"] as Customer) != null)
            {
                if ((Session["vip"] as Customer).Monthly == true)
                {
                    orderPage.PaymentRequestModel.ShoppingPrice = t.Price = 0;
                    (Session["vip"] as Customer).Monthly = false;
                    (Session["vip"] as Customer).MonthlyDate = DateTime.Now;
                    return OrderTicketMVC(orderPage, t);
                }
                else if ((Session["vip"] as Customer).FriendPayed != 0)
                {

                    (Session["vip"] as Customer).FriendPayed--;
                    orderPage.PaymentRequestModel.ShoppingPrice = t.Price = 8 * t.Price / 10;
                    return OrderTicketMVC(orderPage, t);
                }
                orderPage.PaymentRequestModel.ShoppingPrice = t.Price = t.Price / 2;
                return OrderTicketMVC(orderPage, t);
            }
            else
            {
                if ((Session["customer"] as Customer).CustomerCategory == CustomerRole.Full)
                {
                    if ((Session["session"] as Session).SessionTime == _mRep.Find(_sRep.Find((Session["session"] as Session).ID).Movie.ID).Seanses[0].SessionTime || DateTime.Now.DayOfWeek == DayOfWeek.Wednesday)
                    {
                        orderPage.PaymentRequestModel.ShoppingPrice = t.Price = t.Price / 2;
                        return OrderTicketMVC(orderPage, t);
                    }
                    orderPage.PaymentRequestModel.ShoppingPrice = t.Price;
                    return OrderTicketMVC(orderPage, t);
                }
                else if ((Session["customer"] as Customer).CustomerCategory == CustomerRole.Student)
                {
                    if ((Session["session"] as Session).SessionTime == _mRep.Find(_sRep.Find((Session["session"] as Session).ID).Movie.ID).Seanses[0].SessionTime || DateTime.Now.DayOfWeek == DayOfWeek.Wednesday)
                    {
                        orderPage.PaymentRequestModel.ShoppingPrice = t.Price = t.Price / 2;
                        return OrderTicketMVC(orderPage, t);
                    }
                    orderPage.PaymentRequestModel.ShoppingPrice = t.Price = 6 * t.Price / 10;
                    return OrderTicketMVC(orderPage, t);
                }
                return View();
            }
            
        }
       
        private ActionResult OrderTicketMVC(OrderPageVM orderPage,Ticket t)
        {
            bool bResult;
            using (HttpClient client = new HttpClient())
            {

                client.BaseAddress = new Uri("http://localhost:58604/api/");
                Task<HttpResponseMessage> response = client.PostAsJsonAsync("Payment/RecivePayment", orderPage.PaymentRequestModel);
                HttpResponseMessage result;
                try
                {
                    result = response.Result;
                }
                catch (Exception)
                {

                    TempData["baglantiRed"] = "Banka baglantiyi Reddetti";
                    return RedirectToAction("MovieList");
                }
                if (result.IsSuccessStatusCode) bResult = true;
                else bResult = false;
                if (bResult)
                {
                    Order o = new Order();
                    o.OrderType = OrderType.Internet;
                    if (Session["customer"] as Customer != null)
                    {
                        o.Customer = Session["customer"] as Customer;
                        o.MailAddress = (Session["customer"] as Customer).Email;

Project.MVCUI/Views/TicketShopping/ConfirmOrder.cshtml
@model OrderPageVM
@{
    ViewBag.Title = "ConfirmOrder";
}

<script>
    function yesOrNo() {
        document.getElementById("yes").value = true
    }
</script>
<div>
    <h1>@TempData["sorun"]</h1>
    <h1>@TempData["baglantiRed"]</h1>
    @using (Html.BeginForm())
    {
        <div class="form-group">
            <label style="padding-top:10px" class="col-sm-2 control-label">Kart Üzarndeki isim</label>
            <div style="padding-top:10px" class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentRequestModel.CardUserName, new { @class = "form-control" })
            </div>

        </div>

        <div class="form-group">
            <label style="padding-top:10px" class="col-sm-2 control-label">Kart Numarası</label>
            <div style="padding-top:10px" class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentRequestModel.CardNumber, new { @class = "form-control" })
            </div>

        </div>

        <div class="form-group">
            <label style="padding-top:10px" class="col-sm-2 control-label">Kart Güvenlik Numarası</label>
            <div style="padding-top:10px" class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentRequestModel.SecurityNumber, new { @class = "form-control" })
            </div>

        </div>

        <div class="form-group">
            <label style="padding-top:10px" class="col-sm-2 control-label">Gecerlilik Süresi (Yıl)</label>
            <div style="padding-top:10px" class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentRequestModel.CardExpiryYear, new { @class = "form-control" })
            </div>

        </div>

        <div class="form-group">
            <label style="padding-top:10px" class="col-sm-2 control-label">Gecerlilik Süresi (Ay)</label>
            <div style="padding-top:10px" class="col-sm-10">
                @Html.TextBoxFor(x => x.PaymentRequestModel.CardExpiryMonth, new { @class = "form-control" })
            </div>

        </div>
        <div class="form-group">
            <label style="padding-top:10px" class="col-sm-2 control-label">Kayıtlı Kartı Kullanmak için</label>
            <div style="padding-top:10px" class="col-sm-10">
                <input type="checkbox" onclick="yesOrNo()" />
            </div>
        </div>
        <div class="form-group">
            <label style="padding-top:10px" class="col-sm-2 control-label">Onaylamk için TIklayınız</label>
            <div style="padding-top:10px" class="col-sm-10">
                <button class="btn btn-primary">Onayla</button>
            </div>

        </div>

        @Html.HiddenFor(x => x.Save, new { id = "yes" })
    }

</div>

Project.MVCUI/Views/TicketShopping/MakeReservation.cshtml
@model ListSeatPageVM
@{
    ViewBag.Title = "MakeReservation";
}

<head>
    <script>
        function getSeatNumber(button) {
            document.getElementById('rezSeatNumber').value = button.name;
            button.style.backgroundColor = 'yellow';
        }
        function getTime() {
            document.getElementById('hiddenTime').value = document.getElementById('datePicker').value;
        }
    </script>
    <style>
        .sahne {
            height: 50px;
            width: 220px;
            color: aqua;
            text-align: center;
            background-color: blue;
        }
        .seat {
            background-color: green;
            height: 50px;
            width: 50px;
            margin: 3px;
            display: inline-block;
            cursor: pointer;
            color: black;
        }
        .row {
            display: flex
        }
        .sira {
            position: relative;
            left: 300px;
            bottom: 50px;
        }
    </style>
</head>
<body>
    <h1>@TempData["var"]</h1>
    <h1>@TempData["badsession"]</h1>
    @using (Html.BeginForm("MakeReservation", "Ticketshopping", new { salonNo = Model.Movie.SalonNo, filmTitle = Model.Movie.FilmTitle }, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.DropDownListFor(x => x.Reservation.ID, new SelectList(Model.Sessions, "ID", "SessionTime"), "Seans Seciniz", new { @class = "form-control" })
        <input type="date" id="datePicker" onchange="getTime()" class="form-control" />
        <div class="sira">
            <div class="sahne">Sahne</div>
            <div class="row">
                <button class="seat" name="lblA1" onclick="getSeatNumber(this)">A1</button>
                <button class="seat" name="lblA2" onclick="getSeatNumber(this)">A2</button>
                <button class="seat" name="lblA3" onclick="getSeatNumber(this)">A3</button>
            </div>
            <div class="row">
                <button class="seat" name="lblB1" onclick="getSeatNumber(this)">B1</button>
                <button class="seat" name="lblB2" onclick="getSeatNumber(this)">B2</button>
                <button class="seat" name="lblB3" onclick="getSeatNumber(this)">B3</button>
                <button class="seat" name="lblB4" onclick="getSeatNumber(this)">B4</button>
            </div>
            <div class="row">
                <button class="seat" name="lblC1" onclick="getSeatNumber(this)">C1</button>
                <button class="seat" name="lblC2" onclick="getSeatNumber(this)">C2</button>
                <button class="seat" name="lblC3" onclick="getSeatNumber(this)">C3</button>
            </div>
            <div class="row">
                <button class="seat" name="lblD1" onclick="getSeatNumber(this)">D1</button>
                <button class="seat" name="lblD2" onclick="getSeatNumber(this)">D2</button>
                <button class="seat" name="lblD3" onclick="getSeatNumber(this)">D3</button>
                <button class="seat" name="lblD4" onclick="getSeatNumber(this)">D4</button>
            </div>
        </div>
        @Html.HiddenFor(x => x.Reservation.ResSeatNumber, new { id = "rezSeatNumber" })
        @Html.HiddenFor(x => x.Reservation.SessionTime, new { id = "hiddenTime" })
    }
</body>

Project.MVCUI/Views/TicketShopping/MovieList.cshtml
@model ListMoviePageVM
@{
    ViewBag.Title = "MovieList";
}


<table class="table table-hover">
    <tr>
        <th>FilmTitle</th>
        <th></th>
        <th style="position:relative;left:210px">Islemler</th>
        <th></th>
        

    </tr>
    
    @foreach (MovieVM item in Model.Movies)
    {
        <tr>
            <td>@item.FilmTitle</td>
            <td><img src="/Pictures/@item.ImagePath" alt="Resim yok" width="200" height="250" title="@item.FilmTitle" /></td>
            <td>@Html.ActionLink("MakeReservation", "MakeReservation", new { title = item.FilmTitle,}, new { @class = "btn btn-primary" })</td>
            <td>@Html.ActionLink("TakeTicket", "TakeTicket", new { title = item.FilmTitle }, new { @class = "btn btn-primary" })</td>


        </tr>
    }

</table>

Project.MVCUI/Views/TicketShopping/OrderInfo.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OrderInfo</title>
    <link href="~/OuterTools/css/bootstrap.css" rel="stylesheet" />
    <script src="~/OuterTools/js/jquery.js"></script>
    <script src="~/OuterTools/js/bootstrap.js"></script>
    <script>
        $(function () {
            setTimeout(function () {
                window.location = "/TicketShopping/MovieList"
            },10000)
        })

        
    </script>
</head>
<body>
    <div class="jumbotron">

        Congratulations, your payment has been received. The necessary information has been sent to your e-mail address.
    </div>
</body>
</html>

Project.MVCUI/Views/TicketShopping/ReservationInfo.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ReservationInfo</title>
    <link href="~/OuterTools/css/bootstrap.css" rel="stylesheet" />
    <script src="~/OuterTools/js/jquery.js"></script>
    <script src="~/OuterTools/js/bootstrap.js"></script>
    <script>

        $(function () {

            setTimeout(function () {

                window.location = "/TicketShopping/MovieList"

            }, 10000)

        })

    </script>
</head>
<body>
    <div class="jumbotron">

        Congratulations, your reservation has been made successfully. Please confirm it at the box office 30 minutes before the session, otherwise it will be cancelled.
    </div>
</body>
</html>

Project.MVCUI/Views/TicketShopping/TakeTicket.cshtml
@model ListSeatPageVM
@{
    ViewBag.Title = "TakeTicket";
}


<head>
    <script>
        function showTickets(button) {
        
        }
        function getSeatNumber(button) {
            document.getElementById('seatNumber').value = button.name;
            button.style.backgroundColor = 'red';
        }
        function getTime() {
            document.getElementById('hiddenTime').value = document.getElementById('datePicker').value;
        }
        function getSession(select) {
            document.getElementById('sessionTime').value = select.value;
        }
    </script>
    <style>

        .sahne {
            height: 50px;
            width: 220px;
            color: aqua;
            text-align: center;
            background-color: blue;
        }

        .seat {
            background-color: green;
            height: 50px;
            width: 50px;
            margin: 3px;
            display: inline-block;
            cursor: pointer;
            color: black;
        }

        .row {
            display: flex
        }

        .sira {
            position: relative;
            left: 300px;
            bottom: 50px;
        }
    </style>
</head>
<body>
    <h1>@TempData["var"]</h1>
    <h1>@TempData["time"]</h1>
    <h1>@TempData["vipbug"]</h1>
    <h1>@TempData["bug"]</h1>
    @using (Html.BeginForm("TakeTicket", "Ticketshopping", new { salonNo = Model.Movie.SalonNo, filmTitle = Model.Movie.FilmTitle }, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <select class="form-control" onchange="getSession(this)">
            <option value="">Seans Seciniz</option>
            @foreach (SessionVM item in Model.Sessions)
            {
                <option>@item.SessionTime</option>
            }
        </select>
        <input type="date" id="datePicker" onchange="getTime()" class="form-control" />
        <div class="sira">
            <div class="sahne">Sahne</div>
            <div class="row">
                <button class="seat" name="lblA1" onclick="getSeatNumber(this)" >A1</button>
                <button class="seat" name="lblA2" onclick="getSeatNumber(this)">A2</button>
                <button class="seat" name="lblA3" onclick="getSeatNumber(this)">A3</button>
            </div>
            <div class="row">
                <button class="seat" name="lblB1" onclick="getSeatNumber(this)">B1</button>
                <button class="seat" name="lblB2" onclick="getSeatNumber(this)">B2</button>
                <button class="seat" name="lblB3" onclick="getSeatNumber(this)">B3</button>
                <button class="seat" name="lblB4" onclick="getSeatNumber(this)">B4</button>
            </div>
            <div class="row">
                <button class="seat" name="lblC1" onclick="getSeatNumber(this)">C1</button>
                <button class="seat" name="lblC2" onclick="getSeatNumber(this)">C2</button>
                <button class="seat" name="lblC3" onclick="getSeatNumber(this)">C3</button>
            </div>
            <div class="row">
                <button class="seat" name="lblD1" onclick="getSeatNumber(this)">D1</button>
                <button class="seat" name="lblD2" onclick="getSeatNumber(this)">D2</button>
                <button class="seat" name="lblD3" onclick="getSeatNumber(this)">D3</button>
                <button class="seat" name="lblD4" onclick="getSeatNumber(this)">D4</button>
            </div>
        </div>
        @Html.HiddenFor(x => x.Ticket.SeatNumber, new { id = "seatNumber" })
        @Html.HiddenFor(x => x.Ticket.TicketDate, new { id = "hiddenTime" })
        @Html.HiddenFor(x =>x.Ticket.SessionTime,new {id = "sessionTime"})
    }
</body>